# Generated by Django 2.1 on 2019-12-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Topmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('icon', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
