# Generated by Django 2.1 on 2019-12-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmenu',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
