# Generated by Django 2.1 on 2019-12-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
    ]
