# Generated by Django 2.1 on 2020-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191220_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='goodscategroy',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='categroy/picture/'),
        ),
    ]
